# stores contact emails for BPL and DC contacts

default: &default
  site_admin: <%= ENV.fetch('EMAIL_SITE_ADMIN', 'site_admin@example.org') %>
  dc_admin: <%= ENV.fetch('EMAIL_DC_ADMIN', 'dc_admin@example.org') %>
  image_requests: <%= ENV.fetch('EMAIL_IMAGE_REQUEST', 'image_request@example.org') %>
  research_question: <%= ENV.fetch('EMAIL_RESEARCH', 'research@example.org') %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
