# stores Curator API url

default: &default
  url: <%= ENV.fetch('CURATOR_API_URL') { Rails.application.credentials[:curator_api_url].to_s } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
