# stores location of static file with GeoJSON FeatureCollection for catalog#map
# Rails.root.to_s + '/' must be appended by methods calling this value (makes specs easier)

default: &default
  filepath: <%= ENV.fetch('GEOJSON_PATH') { Rails.application.credentials.dig(:geojson_static_file, :filepath).to_s } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
