# stores IIIF image server url

default: &default
  url: <%= ENV.fetch('IIIF_URL') { Rails.application.credentials[:iiif_url].to_s } %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
