# stores secret_key_base for config/initializers/secret_token.rb
# and secret_key for config/initializers/devise.rb

default: &default
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE', 'yoursecretkeybase123456789abcdefghijklmnopqrstuvwxyz') %>
  devise_secret_key: <%= ENV.fetch('DEVISE_SECRET_KEY', 'yourdevisesecretkey123456789abcdefghijklmnopqrstuvwxyz') %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
