# stores VLR settings

development:
  site: commonwealth
  institution:
    pid: bpl-dev:4q77fr32b

test:
  site: commonwealth
  institution:
      pid: commonwealth:abc123

production:
  site: commonwealth
  institution:
      pid: commonwealth:abc123